[package]
name = "hytale_plugin_init"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
inquire = "0.9.1"
serde = { version = "1.0.228", features = ["derive"] }
tera = "1.20.1"
